"use strict";

var helpers = {
    genCallbackPage: function (params, bgcolor, fgcolor) {
        params = params || {};
        bgcolor = bgcolor || "#fff";
        fgcolor = fgcolor || "silver";
        var html = "";
        html += "<!DOCTYPE html>";
        html += "<html>";
        html += "    <head>";
        html += "        <meta charset=\"UTF-8\" />";
        html += "        <title>Wanashare</title>";
        html += "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />";
        html += "        <style>";
        html += "            html, body {";
        html += "                margin: 0;";
        html += "                padding: 0;";
        html += "                width: 100%;";
        html += "                height: 100%;";
        html += "                background: " + bgcolor + ";";
        html += "            }";
        html += "            @-webkit-keyframes rotate {";
        html += "                  0% { -webkit-transform: rotate( 10deg); }";
        html += "                100% { -webkit-transform: rotate(360deg); }";
        html += "            }";
        html += "            @keyframes rotate {";
        html += "                  0% { transform: rotate( 10deg); }";
        html += "                100% { transform: rotate(360deg); }";
        html += "            }";
        html += "            .loader {";
        html += "                position: absolute;";
        html += "                left: calc(50% - 100px);";
        html += "                top: calc(50% - 100px);";
        html += "                box-sizing: border-box;";
        html += "                width: 200px;";
        html += "                height: 200px;";
        html += "                border-radius: 50%;";
        html += "                border: " + fgcolor + " solid 20px;";
        html += "                border-left-color: transparent;";
        html += "                border-right-color: transparent;";
        html += "                -webkit-animation: rotate 1.3s linear infinite;";
        html += "                animation: rotate 1.3s linear infinite;";
        html += "            }";
        html += "            .loader + .loader {";
        html += "                content: \" \";";
        html += "                width: 150px;";
        html += "                height: 150px;";
        html += "                left: calc(50% - 75px);";
        html += "                top: calc(50% - 75px);";
        html += "                animation-direction: reverse;";
        html += "                -webkit-animation-direction: reverse;";
        html += "            }";
        html += "        </style>";
        html += "    </head>";
        html += "    <body>";
        html += "        <div class=\"loader\"></div>";
        html += "        <div class=\"loader\"></div>";
        html += "        <script>";
        html += "            window.oauth = " + JSON.stringify(params) + ";";
        html += "        </script>";
        html += "    </body>";
        html += "</html>";
        return html;
    }
};

module.exports = helpers;
